[package]
name = "midge"
version = "0.0.3"
description = "Midge — MIDI and MQTT bridge"
authors = ["Grantler Instruments"]
edition = "2021"

[lib]
name = "midge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
midir = "0.10"
rumqttc = { version = "0.24", features = ["websocket"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
uuid = { version = "1.24.0", features = ["v4"] }
url = "2"
